### ISSUE TITLE
US19 navbar routes & css optimization

### ISSUE THREAD

**Issue by gnos28** [WildCodeSchool/RMT-2203-TeamKarma-lions#35]

**Comment by Lora048** [comment]
CSS :
- aérer les icones de navigation
- aligner verticalement les icones
- les faire grossir légèrement au hover avec une animation
- pouvoir être redirigé vers 'home' si on clique sur le logo Lion
- mettre en forme les onglets lors du hover

Routes :
- créer les routes vers les pages à partir de mainpage

**Comment by gnos28** [comment]
délai animation inversé
délai devrai s'appliquer lors du mouseLeave et non lors du mouseEnter
