### ISSUE TITLE
US20 Curiosity Widget finalization2

### ISSUE THREAD

**Issue by gnos28** [WildCodeSchool/RMT-2203-TeamKarma-lions#46]
ajout n° page ✅

lazy loading image

bug avec le state ?? >> vérifier ✅

dans le menu déroulant afficher nombre de photo / caméra ✅

**Comment by ClemDSC** [comment]
bloquer le calendrier pour ne pas pouvoir faire de recherche avant la date d'atterrissage sur Mars, ni après la date du jour ✅
